---
apiVersion: v1
kind: Service
metadata:
  name: ace-demo-01-svc
  namespace: demo-rest-trama
  labels:
    app: ace-demo-01-svc
spec:
  ports:
  - name: socket
    port: 8080
    protocol: TCP
    targetPort: 7800
  selector:
    app: ace-demo-01-pod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ace-demo-01-configmap
  namespace: demo-rest-trama
data:
  ACE_SERVER_NAME: "isdemo"
  ACE_WORKPATH: "/home/aceuser/ace-server"
  LICENSE: "accept"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-demo-01-deployment
  namespace: demo-rest-trama
  labels:
    app: ace-demo-01-deploy
spec:
  selector:
    matchLabels:
      app: ace-demo-01-pod
  replicas: 1
  template:
    metadata:
      name: ace-demo-01-pod
      namespace: demo-rest-trama
      labels:
        app: ace-demo-01-pod
    spec:
      containers:
        - name: ace-demo-01-contenedor
          image: quay.io/ivanstalyn/ace_demo_01:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 3m
              memory: 96Mi
          envFrom:
          - configMapRef:
              name: ace-demo-01-configmap
